name: CI

on:
  push:
    branches: [ master, v_* ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    
    - name: Build project
      run: |
        python setup.py build_ext --inplace
        # Alternative: make build
    
    - name: Run tests
      run: |
        pytest test/ -v
    
  build-cpp:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
    
    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_CUDA=OFF
    
    - name: Build
      run: |
        cd build
        make -j$(nproc)
    
    - name: Run C++ tests
      run: |
        cd build
        if [ -f test/cpp/tiny_torch_cpp_tests ]; then
          ./test/cpp/tiny_torch_cpp_tests
        else
          echo "C++ tests binary not found, skipping..."
        fi
